(clear)
;;;(batch "run.clp.bat")
(load "out.pont")
(load-instances "instances/dishes2.pins")
;(load "/Protege/OntologiaAlimentacion.pont")
;(load-instances "/Protege/OntologiaAlimentacion.pins")
(load "functions.clp")
(load "rules.clp")
(run)
