(clear)
;;;(batch "run.clp.bat")
(load "out.pont")
(load-instances "instances/Courses.pins")
;(load-instances "instances/Ingredients.pins")
(load-instances "instances/IngredientsQuantity.pins")
;(load-instances "instances/Nutrients.pins")
;(load-instances "instances/NutrientsQuantity.pins")
;(load-instances "instances/Disease.pins")
(load-instances "instances/Limitations.pins")
;(load "/Protege/OntologiaAlimentacion.pont")
;(load-instances "/Protege/OntologiaAlimentacion.pins")
(load "functions.clp")
(load "rules.clp")
(run)
